export const sampleNewsData = [
	{
		id: 1,
		title: "Tech Innovation in 2024",
		description:
			"Explore the latest trends and technologies that are shaping the future.,Explore the latest trends and technologies that are shaping the future.,Explore the latest trends and technologies that are shaping the future.",
		date: "2024-11-10",
		category: "Technology",
		imageUrl: "https://via.placeholder.com/300x200?text=Tech+Innovation",
	},
	{
		id: 2,
		title: "New Health Guidelines",
		description:
			"A look into the updated health guidelines for the coming year.",
		date: "2024-11-08",
		category: "Health",
		imageUrl: "https://via.placeholder.com/300x200?text=Health+Guidelines",
	},
	{
		id: 3,
		title: "The Future of Education",
		description: "Innovative education methods that are transforming schools.",
		date: "2024-11-05",
		category: "Education",
		imageUrl: "https://via.placeholder.com/300x200?text=Image+Placeholder",
	},
	{
		id: 3,
		title: "The Future of Education",
		description: "Innovative education methods that are transforming schools.",
		date: "2024-11-05",
		category: "Education",
		imageUrl: "https://via.placeholder.com/300x200?text=Image+Placeholder",
	},
	{
		id: 3,
		title: "The Future of Education",
		description: "Innovative education methods that are transforming schools.",
		date: "2024-11-05",
		category: "Education",
		imageUrl: "https://via.placeholder.com/300x200?text=Image+Placeholder",
	},
	{
		id: 3,
		title: "The Future of Education",
		description: "Innovative education methods that are transforming schools.",
		date: "2024-11-05",
		category: "Education",
		imageUrl: "https://via.placeholder.com/300x200?text=Image+Placeholder",
	},
	{
		id: 3,
		title: "The Future of Education",
		description: "Innovative education methods that are transforming schools.",
		date: "2024-11-05",
		category: "Education",
		imageUrl: "https://via.placeholder.com/300x200?text=Image+Placeholder",
	},
	{
		id: 3,
		title: "The Future of Education",
		description: "Innovative education methods that are transforming schools.",
		date: "2024-11-05",
		category: "Education",
		imageUrl: "https://via.placeholder.com/300x200?text=Image+Placeholder",
	},
	{
		id: 3,
		title: "The Future of Education",
		description: "Innovative education methods that are transforming schools.",
		date: "2024-11-05",
		category: "Education",
		imageUrl: "https://via.placeholder.com/300x200?text=Image+Placeholder",
	},
	{
		id: 3,
		title: "The Future of Education",
		description: "Innovative education methods that are transforming schools.",
		date: "2024-11-05",
		category: "Education",
		imageUrl: "https://via.placeholder.com/300x200?text=Image+Placeholder",
	},
	{
		id: 3,
		title: "The Future of Education",
		description: "Innovative education methods that are transforming schools.",
		date: "2024-11-05",
		category: "Education",
		imageUrl: "https://via.placeholder.com/300x200?text=Image+Placeholder",
	},
	{
		id: 3,
		title: "The Future of Education",
		description: "Innovative education methods that are transforming schools.",
		date: "2024-11-05",
		category: "Education",
		imageUrl: "https://via.placeholder.com/300x200?text=Image+Placeholder",
	},
	{
		id: 3,
		title: "The Future of Education",
		description: "Innovative education methods that are transforming schools.",
		date: "2024-11-05",
		category: "Education",
		imageUrl: "https://via.placeholder.com/300x200?text=Image+Placeholder",
	},
	{
		id: 3,
		title: "The Future of Education",
		description: "Innovative education methods that are transforming schools.",
		date: "2024-11-05",
		category: "Education",
		imageUrl: "https://via.placeholder.com/300x200?text=Image+Placeholder",
	},
	{
		id: 3,
		title: "The Future of Education",
		description: "Innovative education methods that are transforming schools.",
		date: "2024-11-05",
		category: "Education",
		imageUrl: "https://via.placeholder.com/300x200?text=Image+Placeholder",
	},
	{
		id: 3,
		title: "The Future of Education",
		description: "Innovative education methods that are transforming schools.",
		date: "2024-11-05",
		category: "Education",
		imageUrl: "https://via.placeholder.com/300x200?text=Image+Placeholder",
	},
	{
		id: 3,
		title: "The Future of Education",
		description: "Innovative education methods that are transforming schools.",
		date: "2024-11-05",
		category: "Education",
		imageUrl: "https://via.placeholder.com/300x200?text=Image+Placeholder",
	},
	{
		id: 3,
		title: "The Future of Education",
		description: "Innovative education methods that are transforming schools.",
		date: "2024-11-05",
		category: "Education",
		imageUrl: "https://via.placeholder.com/300x200?text=Image+Placeholder",
	},
	{
		id: 3,
		title: "The Future of Education",
		description: "Innovative education methods that are transforming schools.",
		date: "2024-11-05",
		category: "Education",
		imageUrl: "https://via.placeholder.com/300x200?text=Image+Placeholder",
	},
	{
		id: 3,
		title: "The Future of Education",
		description: "Innovative education methods that are transforming schools.",
		date: "2024-11-05",
		category: "Education",
		imageUrl: "https://via.placeholder.com/300x200?text=Image+Placeholder",
	},
	{
		id: 3,
		title: "The Future of Education",
		description: "Innovative education methods that are transforming schools.",
		date: "2024-11-05",
		category: "Education",
		imageUrl: "https://via.placeholder.com/300x200?text=Image+Placeholder",
	},
	{
		id: 3,
		title: "The Future of Education",
		description: "Innovative education methods that are transforming schools.",
		date: "2024-11-05",
		category: "Education",
		imageUrl: "https://via.placeholder.com/300x200?text=Image+Placeholder",
	},
	{
		id: 3,
		title: "The Future of Education",
		description: "Innovative education methods that are transforming schools.",
		date: "2024-11-05",
		category: "Education",
		imageUrl: "https://via.placeholder.com/300x200?text=Image+Placeholder",
	},
	{
		id: 3,
		title: "The Future of Education",
		description: "Innovative education methods that are transforming schools.",
		date: "2024-11-05",
		category: "Education",
		imageUrl: "https://via.placeholder.com/300x200?text=Image+Placeholder",
	},
	// Add more sample news items as needed
];
