export const sampleProducts = [
	{
		id: 1,
		imageUrl:
			"https://www.fraction9coffee.com/cdn/shop/t/23/assets/placeholder_600x.png?v=113555733946226816651714543406",
		title: "Kabel NYAF",
		description:
			"Kabel tembaga serabut dengan isolasi PVC berbagai warna seperti biru, merah, hitam, kuning, kuning-hijau.",
		spec: "NYAF 1X0.75 mm (fx) 500V SNI04-6629.3 :C10",
		specDesc:
			"Flexible copper cable with PVC insulation, suitable for general electrical installations.",
		category: "Low Voltage Cables",
		linkTokopedia: "#",
		linkShopee: "#",
		catalogLink: "#",
	},
	{
		id: 2,
		imageUrl:
			"https://www.fraction9coffee.com/cdn/shop/t/23/assets/placeholder_600x.png?v=113555733946226816651714543406",
		title: "Kabel Tembaga",
		description:
			"Kabel tembaga berkualitas tinggi untuk penggunaan rumah dan industri.",
		spec: "NYA 1X2.5 mm 500V",
		specDesc: "High-quality copper cable for residential and industrial use.",
		category: "Low Voltage Cables",
		linkTokopedia: "#",
		linkShopee: "#",
		catalogLink: "#",
	},
	{
		id: 3,
		imageUrl:
			"https://www.fraction9coffee.com/cdn/shop/t/23/assets/placeholder_600x.png?v=113555733946226816651714543406",
		title: "Kabel PVC",
		description:
			"Kabel dengan isolasi PVC untuk instalasi listrik indoor dan outdoor.",
		spec: "PVC 1X4 mm 600V",
		specDesc:
			"PVC insulated cable for indoor and outdoor electrical installations.",
		category: "Low Voltage Cables",
		linkTokopedia: "#",
		linkShopee: "#",
		catalogLink: "#",
	},
	{
		id: 4,
		imageUrl:
			"https://www.fraction9coffee.com/cdn/shop/t/23/assets/placeholder_600x.png?v=113555733946226816651714543406",
		title: "Kabel NYAF 2",
		description:
			"Kabel fleksibel dengan lapisan PVC yang cocok untuk panel listrik.",
		spec: "NYAF 2X0.75 mm 500V",
		specDesc:
			"Flexible cable with PVC insulation, ideal for electrical panel installations.",
		category: "Low Voltage Cables",
		linkTokopedia: "#",
		linkShopee: "#",
		catalogLink: "#",
	},
	{
		id: 5,
		imageUrl:
			"https://www.fraction9coffee.com/cdn/shop/t/23/assets/placeholder_600x.png?v=113555733946226816651714543406",
		title: "Kabel Listrik Panel",
		description: "Kabel listrik untuk panel distribusi dengan pelindung PVC.",
		spec: "NYAF 3X1.5 mm 500V",
		specDesc: "Electrical cable for distribution panels with PVC insulation.",
		category: "Low Voltage Cables",
		linkTokopedia: "#",
		linkShopee: "#",
		catalogLink: "#",
	},
	{
		id: 6,
		imageUrl:
			"https://www.fraction9coffee.com/cdn/shop/t/23/assets/placeholder_600x.png?v=113555733946226816651714543406",
		title: "Kabel Shielded",
		description:
			"Kabel tembaga terkelupas dan dilapisi isolasi PVC untuk proteksi tambahan.",
		spec: "Shielded Cable 2X1 mm",
		specDesc:
			"Shielded copper cable with PVC insulation for additional protection.",
		category: "Medium Voltage Cables",
		linkTokopedia: "#",
		linkShopee: "#",
		catalogLink: "#",
	},
	{
		id: 7,
		imageUrl:
			"https://www.fraction9coffee.com/cdn/shop/t/23/assets/placeholder_600x.png?v=113555733946226816651714543406",
		title: "Kabel Solar Panel",
		description:
			"Kabel tahan cuaca yang cocok untuk penggunaan di sistem tenaga surya.",
		spec: "Kabel PV 6mm 1000V",
		specDesc: "Weather-resistant cable for solar panel systems.",
		category: "Medium Voltage Cables",
		linkTokopedia: "#",
		linkShopee: "#",
		catalogLink: "#",
	},
	{
		id: 8,
		imageUrl:
			"https://www.fraction9coffee.com/cdn/shop/t/23/assets/placeholder_600x.png?v=113555733946226816651714543406",
		title: "Kabel Kontrol",
		description:
			"Kabel kontrol dengan beberapa konduktor untuk penggunaan industri.",
		spec: "Kontrol 5X0.75 mm",
		specDesc:
			"Control cable with multiple conductors for industrial applications.",
		category: "Medium Voltage Cables",
		linkTokopedia: "#",
		linkShopee: "#",
		catalogLink: "#",
	},
	{
		id: 9,
		imageUrl:
			"https://www.fraction9coffee.com/cdn/shop/t/23/assets/placeholder_600x.png?v=113555733946226816651714543406",
		title: "Kabel Tahan Api",
		description:
			"Kabel listrik dengan isolasi tahan api untuk instalasi gedung.",
		spec: "Kabel Tahan Api 1X2.5 mm",
		specDesc: "Fire-resistant cable for building installations.",
		category: "Fire Resistant Cables",
		linkTokopedia: "#",
		linkShopee: "#",
		catalogLink: "#",
	},
	{
		id: 10,
		imageUrl:
			"https://www.fraction9coffee.com/cdn/shop/t/23/assets/placeholder_600x.png?v=113555733946226816651714543406",
		title: "Kabel NYY",
		description: "Kabel NYY dengan pelindung isolasi untuk aplikasi outdoor.",
		spec: "NYY 2X1.5 mm",
		specDesc: "NYY cable with insulation protection for outdoor applications.",
		category: "Low Voltage Cables",
		linkTokopedia: "#",
		linkShopee: "#",
		catalogLink: "#",
	},
	{
		id: 11,
		imageUrl:
			"https://www.fraction9coffee.com/cdn/shop/t/23/assets/placeholder_600x.png?v=113555733946226816651714543406",
		title: "Kabel Flex",
		description: "Kabel fleksibel untuk instalasi elektronik dan peralatan.",
		spec: "Flex 3X0.75 mm",
		specDesc: "Flexible cable for electronics and equipment installations.",
		category: "Flexible Cables",
		linkTokopedia: "#",
		linkShopee: "#",
		catalogLink: "#",
	},
	{
		id: 12,
		imageUrl:
			"https://www.fraction9coffee.com/cdn/shop/t/23/assets/placeholder_600x.png?v=113555733946226816651714543406",
		title: "Kabel Suplai Daya",
		description: "Kabel daya untuk panel distribusi dan perangkat berat.",
		spec: "NYA 4X2.5 mm",
		specDesc: "Power supply cable for distribution panels and heavy equipment.",
		category: "Low Voltage Cables",
		linkTokopedia: "#",
		linkShopee: "#",
		catalogLink: "#",
	},
	{
		id: 13,
		imageUrl:
			"https://www.fraction9coffee.com/cdn/shop/t/23/assets/placeholder_600x.png?v=113555733946226816651714543406",
		title: "Kabel Instalasi Rumah",
		description: "Kabel untuk instalasi listrik di rumah dengan isolasi PVC.",
		spec: "NYAF 3X1.5 mm 500V",
		specDesc: "Cable for home electrical installations with PVC insulation.",
		category: "Low Voltage Cables",
		linkTokopedia: "#",
		linkShopee: "#",
		catalogLink: "#",
	},
	{
		id: 13,
		imageUrl:
			"https://www.fraction9coffee.com/cdn/shop/t/23/assets/placeholder_600x.png?v=113555733946226816651714543406",
		title: "Kabel Instalasi Rumah",
		description: "Kabel untuk instalasi listrik di rumah dengan isolasi PVC.",
		spec: "NYAF 3X1.5 mm 500V",
		specDesc: "Cable for home electrical installations with PVC insulation.",
		category: "Low Voltage Cables",
		linkTokopedia: "#",
		linkShopee: "#",
		catalogLink: "#",
	},
	{
		id: 13,
		imageUrl:
			"https://www.fraction9coffee.com/cdn/shop/t/23/assets/placeholder_600x.png?v=113555733946226816651714543406",
		title: "Kabel Instalasi Rumah",
		description: "Kabel untuk instalasi listrik di rumah dengan isolasi PVC.",
		spec: "NYAF 3X1.5 mm 500V",
		specDesc: "Cable for home electrical installations with PVC insulation.",
		category: "Low Voltage Cables",
		linkTokopedia: "#",
		linkShopee: "#",
		catalogLink: "#",
	},
	{
		id: 13,
		imageUrl:
			"https://www.fraction9coffee.com/cdn/shop/t/23/assets/placeholder_600x.png?v=113555733946226816651714543406",
		title: "Kabel Instalasi Rumah",
		description: "Kabel untuk instalasi listrik di rumah dengan isolasi PVC.",
		spec: "NYAF 3X1.5 mm 500V",
		specDesc: "Cable for home electrical installations with PVC insulation.",
		category: "Low Voltage Cables",
		linkTokopedia: "#",
		linkShopee: "#",
		catalogLink: "#",
	},
	{
		id: 13,
		imageUrl:
			"https://www.fraction9coffee.com/cdn/shop/t/23/assets/placeholder_600x.png?v=113555733946226816651714543406",
		title: "Kabel Instalasi Rumah",
		description: "Kabel untuk instalasi listrik di rumah dengan isolasi PVC.",
		spec: "NYAF 3X1.5 mm 500V",
		specDesc: "Cable for home electrical installations with PVC insulation.",
		category: "Low Voltage Cables",
		linkTokopedia: "#",
		linkShopee: "#",
		catalogLink: "#",
	},
	{
		id: 13,
		imageUrl:
			"https://www.fraction9coffee.com/cdn/shop/t/23/assets/placeholder_600x.png?v=113555733946226816651714543406",
		title: "Kabel Instalasi Rumah",
		description: "Kabel untuk instalasi listrik di rumah dengan isolasi PVC.",
		spec: "NYAF 3X1.5 mm 500V",
		specDesc: "Cable for home electrical installations with PVC insulation.",
		category: "Low Voltage Cables",
		linkTokopedia: "#",
		linkShopee: "#",
		catalogLink: "#",
	},
	{
		id: 13,
		imageUrl:
			"https://www.fraction9coffee.com/cdn/shop/t/23/assets/placeholder_600x.png?v=113555733946226816651714543406",
		title: "Kabel Instalasi Rumah",
		description: "Kabel untuk instalasi listrik di rumah dengan isolasi PVC.",
		spec: "NYAF 3X1.5 mm 500V",
		specDesc: "Cable for home electrical installations with PVC insulation.",
		category: "Low Voltage Cables",
		linkTokopedia: "#",
		linkShopee: "#",
		catalogLink: "#",
	},
	{
		id: 13,
		imageUrl:
			"https://www.fraction9coffee.com/cdn/shop/t/23/assets/placeholder_600x.png?v=113555733946226816651714543406",
		title: "Kabel Instalasi Rumah",
		description: "Kabel untuk instalasi listrik di rumah dengan isolasi PVC.",
		spec: "NYAF 3X1.5 mm 500V",
		specDesc: "Cable for home electrical installations with PVC insulation.",
		category: "Low Voltage Cables",
		linkTokopedia: "#",
		linkShopee: "#",
		catalogLink: "#",
	},
	{
		id: 13,
		imageUrl:
			"https://www.fraction9coffee.com/cdn/shop/t/23/assets/placeholder_600x.png?v=113555733946226816651714543406",
		title: "Kabel Instalasi Rumah",
		description: "Kabel untuk instalasi listrik di rumah dengan isolasi PVC.",
		spec: "NYAF 3X1.5 mm 500V",
		specDesc: "Cable for home electrical installations with PVC insulation.",
		category: "Low Voltage Cables",
		linkTokopedia: "#",
		linkShopee: "#",
		catalogLink: "#",
	},
	{
		id: 13,
		imageUrl:
			"https://www.fraction9coffee.com/cdn/shop/t/23/assets/placeholder_600x.png?v=113555733946226816651714543406",
		title: "Kabel Instalasi Rumah",
		description: "Kabel untuk instalasi listrik di rumah dengan isolasi PVC.",
		spec: "NYAF 3X1.5 mm 500V",
		specDesc: "Cable for home electrical installations with PVC insulation.",
		category: "Low Voltage Cables",
		linkTokopedia: "#",
		linkShopee: "#",
		catalogLink: "#",
	},
	{
		id: 13,
		imageUrl:
			"https://www.fraction9coffee.com/cdn/shop/t/23/assets/placeholder_600x.png?v=113555733946226816651714543406",
		title: "Kabel Instalasi Rumah",
		description: "Kabel untuk instalasi listrik di rumah dengan isolasi PVC.",
		spec: "NYAF 3X1.5 mm 500V",
		specDesc: "Cable for home electrical installations with PVC insulation.",
		category: "Low Voltage Cables",
		linkTokopedia: "#",
		linkShopee: "#",
		catalogLink: "#",
	},
	{
		id: 13,
		imageUrl:
			"https://www.fraction9coffee.com/cdn/shop/t/23/assets/placeholder_600x.png?v=113555733946226816651714543406",
		title: "Kabel Instalasi Rumah",
		description: "Kabel untuk instalasi listrik di rumah dengan isolasi PVC.",
		spec: "NYAF 3X1.5 mm 500V",
		specDesc: "Cable for home electrical installations with PVC insulation.",
		category: "Low Voltage Cables",
		linkTokopedia: "#",
		linkShopee: "#",
		catalogLink: "#",
	},
	{
		id: 13,
		imageUrl:
			"https://www.fraction9coffee.com/cdn/shop/t/23/assets/placeholder_600x.png?v=113555733946226816651714543406",
		title: "Kabel Instalasi Rumah",
		description: "Kabel untuk instalasi listrik di rumah dengan isolasi PVC.",
		spec: "NYAF 3X1.5 mm 500V",
		specDesc: "Cable for home electrical installations with PVC insulation.",
		category: "Low Voltage Cables",
		linkTokopedia: "#",
		linkShopee: "#",
		catalogLink: "#",
	},
	{
		id: 13,
		imageUrl:
			"https://www.fraction9coffee.com/cdn/shop/t/23/assets/placeholder_600x.png?v=113555733946226816651714543406",
		title: "Kabel Instalasi Rumah",
		description: "Kabel untuk instalasi listrik di rumah dengan isolasi PVC.",
		spec: "NYAF 3X1.5 mm 500V",
		specDesc: "Cable for home electrical installations with PVC insulation.",
		category: "Low Voltage Cables",
		linkTokopedia: "#",
		linkShopee: "#",
		catalogLink: "#",
	},
];
